### ISSUE TITLE
Error when new install

### ISSUE THREAD

**Issue by chanharryc** [horryruo/multi-bot#13]
安排後當執行時出現以下情況，請問如何解決，謝謝!

Traceback (most recent call last):
  File "mybot.py", line 5, in <module>
    from app.utils import func_handler, task
  File "/home/chanharry/multi-bot/app/utils/task.py", line 5, in <module>
    from app.utils.magnet import sukebei
  File "/home/chanharry/multi-bot/app/utils/magnet.py", line 8, in <module>
    from jinja2 import PackageLoader,Environment
  File "/home/chanharry/.local/lib/python3.8/site-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/home/chanharry/.local/lib/python3.8/site-packages/jinja2/environment.py", line 15, in <module>
    from jinja2 import nodes
  File "/home/chanharry/.local/lib/python3.8/site-packages/jinja2/nodes.py", line 19, in <module>
    from jinja2.utils import Markup
  File "/home/chanharry/.local/lib/python3.8/site-packages/jinja2/utils.py", line 624, in <module>
    from markupsafe import Markup, escape, soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/home/chanharry/.local/lib/python3.8/site-packages/markupsafe/__init__.py)

**Comment by horryruo** [comment]
似乎是 markupsafe 升级导致jinja2无法使用，尝试将其降级看看`pip install markupsafe==2.0.1`
